dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
sudo: required

services:
  - docker

before_install:
  - docker build -t backend_flask .

script:
  - docker run backend_flask nose2 -v

after_success:
  - test $TRAVIS_BRANCH != "master" || test $TRAVIS_BRANCH != "master" && echo "branch is not master, will not deploy."  && exit 0
  - ( echo "$HEROKU_USERNAME" echo "$HEROKU_API_KEY" ) | heroku login -i
  - heroku container:login
  - heroku container:push web --app $HEROKU_APP_NAME
  - heroku container:release web --app $HEROKU_APP_NAME
