dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - nose2 -v
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  on:
    all_branches: true
  app: stock-price-sentiment
  run: 
    - heroku container:login
    - docker build -t backend_flask .
    - heroku container:push web --app stock-price-sentiment
    - heroku container:release web --app stock-price-sentiment
