version: "3"
services:
  flask:
    build: .
    container_name: flask
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - PYTHONUNBUFFERED=0
    
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
