version: '3'
services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    expose: 
      - 8080
    volumes:
      - ./flask:/code
  postgres:
    image: "postgres:latest"
    expose: 
      - 5432
    container_name: postgres
    environment: 
      POSTGRES_PASSWORD: password
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
