version: "3"
services:
  flask:
    build: .
    container_name: flask
    volumes:
      - .:/app
    ports:
      - "5000:5000"
<<<<<<< HEAD
    volumes:
      - .:/code
=======
>>>>>>> 57c3c1bc7c913a367757605f6667af551c269805
    environment:
      - PORT=5000
      - PYTHONUNBUFFERED=0
    links:
      - postgres
  postgres:
    image: "postgres:latest"
    expose:
      - "5432"
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
